version: '2'
services:
  web:
    container_name: newvp_web
    build: web
    restart: always
    cpuset: 0-6
    volumes:
      - ../ips:/var/www
    ports:
      - "8089:80"
    extra_hosts:
     - "mysql:172.18.0.1"
#    links:
#      - mysql
#  mysql:
#    container_name: newvp_mysql
#    image: mysql
#    ports:
#      - "3307:3306"
#    restart: always
#    volumes:
#      - ../db:/var/lib/mysql
#      - ../sql:/home/root 
#    environment:
#      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  mail:
    container_name: newvp_mail
    build: exim4
    restart: always
