version: '2'
services:
  web_dev:
    container_name: vp_dev_web
    build: web_dev
    cpuset: "7"
    volumes:
      - ../ips_dev:/var/www
    ports:
      - "8090:80"
    restart: always
    links:
      - vp_dev_mysql
  vp_dev_mysql:
    container_name: vp_dev_mysql
    image: mysql
    ports:
      - "3308:3306"
    restart: always
    volumes:
      - ../db:/var/lib/mysql
      - ../sql:/home/root 
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  mail_dev:
    container_name: vp_dev_mail
    build: mailtrap
    restart: always
